WINDOW_WIDTH = 640
WINDOW_HEIGHT = 360
WINDOW_SIZE = WINDOW_WIDTH, WINDOW_HEIGHT

WINDOW_SCALE = 2
SCALED_WINDOW_SIZE = WINDOW_WIDTH*WINDOW_SCALE, WINDOW_HEIGHT*WINDOW_SCALE

FRAMERATE = 100

CAPTION = "LD56"

QWERTY_LAYOUT = "QWERTYUIOP", "ASDFGHJKL", "ZXCVBNM"

ALL_LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
RARE_LETTERS = "QZXJ"
UNCOMMON_LETTERS = "KVBPGWY"
COMMON_LETTERS = "".join(letter for letter in ALL_LETTERS if letter not in RARE_LETTERS + UNCOMMON_LETTERS)

RIGHT = 0
UP_RIGHT = 1
UP_LEFT = 2
LEFT = 3
DOWN_LEFT = 4
DOWN_RIGHT = 5

PLAYER_TURN = 0
DAMAGE = 1
ANT_TURN = 2
